#ifndef CS_MANAGER_H_
#define CS_MANAGER_H_

#include <peripheralManager/USART_manager.h>

typedef enum{
	NETWORK_REGISTRATION_NOT_REGISTERED = 			0,
	NETWORK_REGISTRATION_REGISTERED_HOME = 			1,
	NETWORK_REGISTRATION_NOT_REGISTERED_SEARCHING = 2,
	NETWORK_REGISTRATION_DENIED = 					3,
	NETWORK_REGISTRATION_UNKNOWN = 					4,
	NETWORK_REGISTRATION_REGISTERED_ROAMING = 		5,
}E_NETWORK_REGISTRATION_STATUS;


#endif /* CS_MANAGER_H_ */